library(devtools)
cat("Instalando pacote...\n")
devtools::install(".", quiet = TRUE)
cat("Carregando pacote...\n")
library(imasul)
cat("Testando carregar_dados_imasul()...\n")
dados <- carregar_dados_imasul()
cat("Sucesso! Carregados", nrow(dados), "registros\n")
q("no")
